// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

void Vtop___024root__trace_chg_top_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_top_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[1U] 
                     | vlSelf->__Vm_traceActivity[0xdU]))) {
        bufp->chgBit(oldp+0,(vlSymsp->TOP__top.__PVT__reset));
        bufp->chgIData(oldp+1,(vlSymsp->TOP__top.__PVT__memreq_msg_addr),32);
        bufp->chgIData(oldp+2,(vlSymsp->TOP__top.__PVT__memreq_msg_data),32);
        bufp->chgIData(oldp+3,(vlSymsp->TOP__top.__PVT__cache_resp_msg_data),32);
        bufp->chgBit(oldp+4,(vlSymsp->TOP__top.__PVT__reg_en_M0));
        bufp->chgBit(oldp+5,(vlSymsp->TOP__top.__PVT__tarray_en));
        bufp->chgBit(oldp+6,(vlSymsp->TOP__top.__PVT__tarray_en2));
        bufp->chgBit(oldp+7,(vlSymsp->TOP__top.__PVT__tarray_wen));
        bufp->chgBit(oldp+8,(vlSymsp->TOP__top.__PVT__tarray_wen2));
        bufp->chgBit(oldp+9,(vlSymsp->TOP__top.__PVT__z6b_sel));
        bufp->chgBit(oldp+10,(vlSymsp->TOP__top.__PVT__darray_write_mux_sel));
        bufp->chgBit(oldp+11,(vlSymsp->TOP__top.__PVT__darray_wen));
        bufp->chgBit(oldp+12,(vlSymsp->TOP__top.__PVT__darray_wen2));
        bufp->chgBit(oldp+13,(vlSymsp->TOP__top.__PVT__write_en_sel));
        bufp->chgBit(oldp+14,(vlSymsp->TOP__top.__PVT__spill_one_word_done));
        bufp->chgBit(oldp+15,(vlSymsp->TOP__top.__PVT__refill_one_word_req_sent));
        bufp->chgBit(oldp+16,(vlSymsp->TOP__top.__PVT__refill_one_word_resp_received));
        bufp->chgBit(oldp+17,(vlSymsp->TOP__top.__PVT__Spill_or_Refill_sel));
        bufp->chgBit(oldp+18,(vlSymsp->TOP__top.__PVT__flush));
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[2U])) {
        bufp->chgBit(oldp+19,(vlSymsp->TOP__top.clk));
        bufp->chgBit(oldp+20,(vlSymsp->TOP__top.linetrace));
        bufp->chgBit(oldp+21,(vlSymsp->TOP__top__DUT.__PVT__clk));
        bufp->chgBit(oldp+22,(vlSymsp->TOP__top__DUT__cache_request_addr_reg_M0.__PVT__clk));
        bufp->chgBit(oldp+23,(vlSymsp->TOP__top__DUT__cache_request_data_reg_M0.__PVT__clk));
    }
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[3U] 
                     | vlSelf->__Vm_traceActivity[5U]))) {
        bufp->chgBit(oldp+24,(vlSymsp->TOP__top__DUT.__PVT__reset));
        bufp->chgIData(oldp+25,(vlSymsp->TOP__top__DUT.__PVT__memreq_msg_addr),32);
        bufp->chgIData(oldp+26,(vlSymsp->TOP__top__DUT.__PVT__memreq_msg_data),32);
        bufp->chgIData(oldp+27,(vlSymsp->TOP__top__DUT.__PVT__cache_resp_msg_data),32);
        bufp->chgBit(oldp+28,(vlSymsp->TOP__top__DUT.__PVT__reg_en_M0));
        bufp->chgBit(oldp+29,(vlSymsp->TOP__top__DUT.__PVT__tarray_en));
        bufp->chgBit(oldp+30,(vlSymsp->TOP__top__DUT.__PVT__tarray_en2));
        bufp->chgBit(oldp+31,(vlSymsp->TOP__top__DUT.__PVT__tarray_wen));
        bufp->chgBit(oldp+32,(vlSymsp->TOP__top__DUT.__PVT__tarray_wen2));
        bufp->chgBit(oldp+33,(vlSymsp->TOP__top__DUT.__PVT__z6b_sel));
        bufp->chgBit(oldp+34,(vlSymsp->TOP__top__DUT.__PVT__darray_write_mux_sel));
        bufp->chgBit(oldp+35,(vlSymsp->TOP__top__DUT.__PVT__darray_wen));
        bufp->chgBit(oldp+36,(vlSymsp->TOP__top__DUT.__PVT__darray_wen2));
        bufp->chgBit(oldp+37,(vlSymsp->TOP__top__DUT.__PVT__write_en_sel));
        bufp->chgBit(oldp+38,(vlSymsp->TOP__top__DUT.__PVT__spill_one_word_done));
        bufp->chgBit(oldp+39,(vlSymsp->TOP__top__DUT.__PVT__refill_one_word_req_sent));
        bufp->chgBit(oldp+40,(vlSymsp->TOP__top__DUT.__PVT__refill_one_word_resp_received));
        bufp->chgBit(oldp+41,(vlSymsp->TOP__top__DUT.__PVT__Spill_or_Refill_sel));
        bufp->chgBit(oldp+42,(vlSymsp->TOP__top__DUT.__PVT__flush));
        bufp->chgBit(oldp+43,(vlSymsp->TOP__top__DUT__z6b_mux.__PVT__sel));
        bufp->chgBit(oldp+44,(vlSymsp->TOP__top__DUT__Spill_or_Refill_Mux.__PVT__sel));
        bufp->chgBit(oldp+45,(vlSymsp->TOP__top__DUT__spill_index_mux.__PVT__sel));
        bufp->chgBit(oldp+46,(vlSymsp->TOP__top__DUT__darray_write_mux.__PVT__sel));
        bufp->chgBit(oldp+47,(vlSymsp->TOP__top__DUT__word_en_mux.__PVT__sel));
    }
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[3U] 
                     | vlSelf->__Vm_traceActivity[8U]))) {
        bufp->chgBit(oldp+48,(vlSymsp->TOP__top__DUT__cache_request_addr_reg_M0.__PVT__reset));
        bufp->chgIData(oldp+49,(vlSymsp->TOP__top__DUT__cache_request_addr_reg_M0.__PVT__d),32);
        bufp->chgBit(oldp+50,(vlSymsp->TOP__top__DUT__cache_request_addr_reg_M0.__PVT__en));
        bufp->chgBit(oldp+51,(vlSymsp->TOP__top__DUT__cache_request_data_reg_M0.__PVT__reset));
        bufp->chgIData(oldp+52,(vlSymsp->TOP__top__DUT__cache_request_data_reg_M0.__PVT__d),32);
        bufp->chgBit(oldp+53,(vlSymsp->TOP__top__DUT__cache_request_data_reg_M0.__PVT__en));
    }
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[3U] 
                     | vlSelf->__Vm_traceActivity[9U]))) {
        bufp->chgWData(oldp+54,(vlSymsp->TOP__top__DUT.__PVT__write_data),512);
        bufp->chgWData(oldp+70,(vlSymsp->TOP__top__DUT__darray_write_mux.__PVT__out),512);
    }
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[3U] 
                     | vlSelf->__Vm_traceActivity[0xbU]))) {
        bufp->chgIData(oldp+86,(vlSymsp->TOP__top.__PVT__memresp_msg_data),32);
        bufp->chgIData(oldp+87,(vlSymsp->TOP__top.__PVT__cache_req_msg_data),32);
        bufp->chgBit(oldp+88,(vlSymsp->TOP__top.__PVT__tarray_match));
        bufp->chgBit(oldp+89,(vlSymsp->TOP__top.__PVT__current_dirty));
        bufp->chgBit(oldp+90,(vlSymsp->TOP__top.__PVT__spill_done));
        bufp->chgBit(oldp+91,(vlSymsp->TOP__top.__PVT__current_lru));
        bufp->chgBit(oldp+92,(vlSymsp->TOP__top.__PVT__flush_dirty));
        bufp->chgIData(oldp+93,(vlSymsp->TOP__top__DUT.__PVT__memresp_msg_data),32);
        bufp->chgIData(oldp+94,(vlSymsp->TOP__top__DUT.__PVT__cache_req_msg_data),32);
        bufp->chgBit(oldp+95,(vlSymsp->TOP__top__DUT.__PVT__tarray_match));
        bufp->chgBit(oldp+96,(vlSymsp->TOP__top__DUT.__PVT__current_dirty));
        bufp->chgBit(oldp+97,(vlSymsp->TOP__top__DUT.__PVT__spill_done));
        bufp->chgBit(oldp+98,(vlSymsp->TOP__top__DUT.__PVT__current_lru));
        bufp->chgBit(oldp+99,(vlSymsp->TOP__top__DUT.__PVT__flush_dirty));
        bufp->chgBit(oldp+100,(vlSymsp->TOP__top__DUT.__PVT__tarray_match1));
        bufp->chgBit(oldp+101,(vlSymsp->TOP__top__DUT.__PVT__tarray_match2));
        bufp->chgIData(oldp+102,(vlSymsp->TOP__top__DUT.__PVT__spill_initial_addr),32);
        bufp->chgIData(oldp+103,(vlSymsp->TOP__top__DUT.__PVT__spill_addr),32);
        bufp->chgCData(oldp+104,(vlSymsp->TOP__top__DUT.__PVT__index_spill),5);
        bufp->chgIData(oldp+105,(vlSymsp->TOP__top__DUT.__PVT__Spill_tag),21);
        bufp->chgIData(oldp+106,(vlSymsp->TOP__top__DUT.__PVT__cache_to_mem_data),32);
        bufp->chgWData(oldp+107,(vlSymsp->TOP__top__DUT.__PVT__data_array_output),512);
        bufp->chgBit(oldp+123,(vlSymsp->TOP__top__DUT__FLush_dirty_mux.__PVT__in0));
        bufp->chgBit(oldp+124,(vlSymsp->TOP__top__DUT__FLush_dirty_mux.__PVT__in1));
        bufp->chgBit(oldp+125,(vlSymsp->TOP__top__DUT__FLush_dirty_mux.__PVT__sel));
        bufp->chgBit(oldp+126,(vlSymsp->TOP__top__DUT__FLush_dirty_mux.__PVT__out));
        bufp->chgIData(oldp+127,(vlSymsp->TOP__top__DUT__Spill_or_Refill_Mux.__PVT__in0),32);
        bufp->chgCData(oldp+128,(vlSymsp->TOP__top__DUT__spill_index_mux.__PVT__out),5);
        bufp->chgIData(oldp+129,(vlSymsp->TOP__top__DUT__Spill_tag_mux.__PVT__in0),21);
        bufp->chgIData(oldp+130,(vlSymsp->TOP__top__DUT__Spill_tag_mux.__PVT__in1),21);
        bufp->chgBit(oldp+131,(vlSymsp->TOP__top__DUT__Spill_tag_mux.__PVT__sel));
        bufp->chgIData(oldp+132,(vlSymsp->TOP__top__DUT__Spill_tag_mux.__PVT__out),21);
        bufp->chgBit(oldp+133,(vlSymsp->TOP__top__DUT__way_output_sel_mux.__PVT__sel));
        bufp->chgWData(oldp+134,(vlSymsp->TOP__top__DUT__way_output_sel_mux.__PVT__out),512);
        bufp->chgIData(oldp+150,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in0),32);
        bufp->chgIData(oldp+151,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in1),32);
        bufp->chgIData(oldp+152,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in2),32);
        bufp->chgIData(oldp+153,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in3),32);
        bufp->chgIData(oldp+154,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in4),32);
        bufp->chgIData(oldp+155,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in5),32);
        bufp->chgIData(oldp+156,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in6),32);
        bufp->chgIData(oldp+157,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in7),32);
        bufp->chgIData(oldp+158,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in8),32);
        bufp->chgIData(oldp+159,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in9),32);
        bufp->chgIData(oldp+160,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in10),32);
        bufp->chgIData(oldp+161,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in11),32);
        bufp->chgIData(oldp+162,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in12),32);
        bufp->chgIData(oldp+163,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in13),32);
        bufp->chgIData(oldp+164,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in14),32);
        bufp->chgIData(oldp+165,(vlSymsp->TOP__top__DUT__output_mux.__PVT__in15),32);
        bufp->chgIData(oldp+166,(vlSymsp->TOP__top__DUT__output_mux.__PVT__out),32);
    }
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[3U] 
                     | vlSelf->__Vm_traceActivity[0xcU]))) {
        bufp->chgIData(oldp+167,(vlSymsp->TOP__top.__PVT__cache_req_msg_addr),32);
        bufp->chgIData(oldp+168,(vlSymsp->TOP__top__DUT.__PVT__cache_req_msg_addr),32);
        bufp->chgIData(oldp+169,(vlSymsp->TOP__top__DUT.__PVT__refill_addr),32);
        bufp->chgIData(oldp+170,(vlSymsp->TOP__top__DUT__Spill_or_Refill_Mux.__PVT__in1),32);
        bufp->chgIData(oldp+171,(vlSymsp->TOP__top__DUT__Spill_or_Refill_Mux.__PVT__out),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[4U])) {
        bufp->chgBit(oldp+172,(vlSymsp->TOP__top.__PVT__refill_req_done));
        bufp->chgBit(oldp+173,(vlSymsp->TOP__top.__PVT__refill_resp_done));
        bufp->chgBit(oldp+174,(vlSymsp->TOP__top.__PVT__flush_done));
        bufp->chgBit(oldp+175,(vlSymsp->TOP__top__DUT.__PVT__refill_req_done));
        bufp->chgBit(oldp+176,(vlSymsp->TOP__top__DUT.__PVT__refill_resp_done));
        bufp->chgBit(oldp+177,(vlSymsp->TOP__top__DUT.__PVT__flush_done));
        bufp->chgIData(oldp+178,(vlSymsp->TOP__top__DUT.__PVT__tag_array[0]),21);
        bufp->chgIData(oldp+179,(vlSymsp->TOP__top__DUT.__PVT__tag_array[1]),21);
        bufp->chgIData(oldp+180,(vlSymsp->TOP__top__DUT.__PVT__tag_array[2]),21);
        bufp->chgIData(oldp+181,(vlSymsp->TOP__top__DUT.__PVT__tag_array[3]),21);
        bufp->chgIData(oldp+182,(vlSymsp->TOP__top__DUT.__PVT__tag_array[4]),21);
        bufp->chgIData(oldp+183,(vlSymsp->TOP__top__DUT.__PVT__tag_array[5]),21);
        bufp->chgIData(oldp+184,(vlSymsp->TOP__top__DUT.__PVT__tag_array[6]),21);
        bufp->chgIData(oldp+185,(vlSymsp->TOP__top__DUT.__PVT__tag_array[7]),21);
        bufp->chgIData(oldp+186,(vlSymsp->TOP__top__DUT.__PVT__tag_array[8]),21);
        bufp->chgIData(oldp+187,(vlSymsp->TOP__top__DUT.__PVT__tag_array[9]),21);
        bufp->chgIData(oldp+188,(vlSymsp->TOP__top__DUT.__PVT__tag_array[10]),21);
        bufp->chgIData(oldp+189,(vlSymsp->TOP__top__DUT.__PVT__tag_array[11]),21);
        bufp->chgIData(oldp+190,(vlSymsp->TOP__top__DUT.__PVT__tag_array[12]),21);
        bufp->chgIData(oldp+191,(vlSymsp->TOP__top__DUT.__PVT__tag_array[13]),21);
        bufp->chgIData(oldp+192,(vlSymsp->TOP__top__DUT.__PVT__tag_array[14]),21);
        bufp->chgIData(oldp+193,(vlSymsp->TOP__top__DUT.__PVT__tag_array[15]),21);
        bufp->chgIData(oldp+194,(vlSymsp->TOP__top__DUT.__PVT__tag_array[16]),21);
        bufp->chgIData(oldp+195,(vlSymsp->TOP__top__DUT.__PVT__tag_array[17]),21);
        bufp->chgIData(oldp+196,(vlSymsp->TOP__top__DUT.__PVT__tag_array[18]),21);
        bufp->chgIData(oldp+197,(vlSymsp->TOP__top__DUT.__PVT__tag_array[19]),21);
        bufp->chgIData(oldp+198,(vlSymsp->TOP__top__DUT.__PVT__tag_array[20]),21);
        bufp->chgIData(oldp+199,(vlSymsp->TOP__top__DUT.__PVT__tag_array[21]),21);
        bufp->chgIData(oldp+200,(vlSymsp->TOP__top__DUT.__PVT__tag_array[22]),21);
        bufp->chgIData(oldp+201,(vlSymsp->TOP__top__DUT.__PVT__tag_array[23]),21);
        bufp->chgIData(oldp+202,(vlSymsp->TOP__top__DUT.__PVT__tag_array[24]),21);
        bufp->chgIData(oldp+203,(vlSymsp->TOP__top__DUT.__PVT__tag_array[25]),21);
        bufp->chgIData(oldp+204,(vlSymsp->TOP__top__DUT.__PVT__tag_array[26]),21);
        bufp->chgIData(oldp+205,(vlSymsp->TOP__top__DUT.__PVT__tag_array[27]),21);
        bufp->chgIData(oldp+206,(vlSymsp->TOP__top__DUT.__PVT__tag_array[28]),21);
        bufp->chgIData(oldp+207,(vlSymsp->TOP__top__DUT.__PVT__tag_array[29]),21);
        bufp->chgIData(oldp+208,(vlSymsp->TOP__top__DUT.__PVT__tag_array[30]),21);
        bufp->chgIData(oldp+209,(vlSymsp->TOP__top__DUT.__PVT__tag_array[31]),21);
        bufp->chgIData(oldp+210,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[0]),21);
        bufp->chgIData(oldp+211,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[1]),21);
        bufp->chgIData(oldp+212,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[2]),21);
        bufp->chgIData(oldp+213,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[3]),21);
        bufp->chgIData(oldp+214,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[4]),21);
        bufp->chgIData(oldp+215,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[5]),21);
        bufp->chgIData(oldp+216,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[6]),21);
        bufp->chgIData(oldp+217,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[7]),21);
        bufp->chgIData(oldp+218,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[8]),21);
        bufp->chgIData(oldp+219,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[9]),21);
        bufp->chgIData(oldp+220,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[10]),21);
        bufp->chgIData(oldp+221,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[11]),21);
        bufp->chgIData(oldp+222,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[12]),21);
        bufp->chgIData(oldp+223,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[13]),21);
        bufp->chgIData(oldp+224,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[14]),21);
        bufp->chgIData(oldp+225,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[15]),21);
        bufp->chgIData(oldp+226,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[16]),21);
        bufp->chgIData(oldp+227,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[17]),21);
        bufp->chgIData(oldp+228,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[18]),21);
        bufp->chgIData(oldp+229,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[19]),21);
        bufp->chgIData(oldp+230,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[20]),21);
        bufp->chgIData(oldp+231,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[21]),21);
        bufp->chgIData(oldp+232,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[22]),21);
        bufp->chgIData(oldp+233,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[23]),21);
        bufp->chgIData(oldp+234,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[24]),21);
        bufp->chgIData(oldp+235,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[25]),21);
        bufp->chgIData(oldp+236,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[26]),21);
        bufp->chgIData(oldp+237,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[27]),21);
        bufp->chgIData(oldp+238,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[28]),21);
        bufp->chgIData(oldp+239,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[29]),21);
        bufp->chgIData(oldp+240,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[30]),21);
        bufp->chgIData(oldp+241,(vlSymsp->TOP__top__DUT.__PVT__tag_array2[31]),21);
        bufp->chgBit(oldp+242,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[0]));
        bufp->chgBit(oldp+243,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[1]));
        bufp->chgBit(oldp+244,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[2]));
        bufp->chgBit(oldp+245,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[3]));
        bufp->chgBit(oldp+246,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[4]));
        bufp->chgBit(oldp+247,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[5]));
        bufp->chgBit(oldp+248,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[6]));
        bufp->chgBit(oldp+249,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[7]));
        bufp->chgBit(oldp+250,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[8]));
        bufp->chgBit(oldp+251,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[9]));
        bufp->chgBit(oldp+252,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[10]));
        bufp->chgBit(oldp+253,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[11]));
        bufp->chgBit(oldp+254,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[12]));
        bufp->chgBit(oldp+255,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[13]));
        bufp->chgBit(oldp+256,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[14]));
        bufp->chgBit(oldp+257,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[15]));
        bufp->chgBit(oldp+258,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[16]));
        bufp->chgBit(oldp+259,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[17]));
        bufp->chgBit(oldp+260,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[18]));
        bufp->chgBit(oldp+261,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[19]));
        bufp->chgBit(oldp+262,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[20]));
        bufp->chgBit(oldp+263,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[21]));
        bufp->chgBit(oldp+264,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[22]));
        bufp->chgBit(oldp+265,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[23]));
        bufp->chgBit(oldp+266,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[24]));
        bufp->chgBit(oldp+267,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[25]));
        bufp->chgBit(oldp+268,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[26]));
        bufp->chgBit(oldp+269,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[27]));
        bufp->chgBit(oldp+270,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[28]));
        bufp->chgBit(oldp+271,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[29]));
        bufp->chgBit(oldp+272,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[30]));
        bufp->chgBit(oldp+273,(vlSymsp->TOP__top__DUT.__PVT__dirty_array[31]));
        bufp->chgBit(oldp+274,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[0]));
        bufp->chgBit(oldp+275,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[1]));
        bufp->chgBit(oldp+276,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[2]));
        bufp->chgBit(oldp+277,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[3]));
        bufp->chgBit(oldp+278,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[4]));
        bufp->chgBit(oldp+279,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[5]));
        bufp->chgBit(oldp+280,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[6]));
        bufp->chgBit(oldp+281,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[7]));
        bufp->chgBit(oldp+282,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[8]));
        bufp->chgBit(oldp+283,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[9]));
        bufp->chgBit(oldp+284,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[10]));
        bufp->chgBit(oldp+285,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[11]));
        bufp->chgBit(oldp+286,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[12]));
        bufp->chgBit(oldp+287,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[13]));
        bufp->chgBit(oldp+288,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[14]));
        bufp->chgBit(oldp+289,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[15]));
        bufp->chgBit(oldp+290,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[16]));
        bufp->chgBit(oldp+291,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[17]));
        bufp->chgBit(oldp+292,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[18]));
        bufp->chgBit(oldp+293,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[19]));
        bufp->chgBit(oldp+294,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[20]));
        bufp->chgBit(oldp+295,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[21]));
        bufp->chgBit(oldp+296,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[22]));
        bufp->chgBit(oldp+297,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[23]));
        bufp->chgBit(oldp+298,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[24]));
        bufp->chgBit(oldp+299,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[25]));
        bufp->chgBit(oldp+300,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[26]));
        bufp->chgBit(oldp+301,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[27]));
        bufp->chgBit(oldp+302,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[28]));
        bufp->chgBit(oldp+303,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[29]));
        bufp->chgBit(oldp+304,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[30]));
        bufp->chgBit(oldp+305,(vlSymsp->TOP__top__DUT.__PVT__dirty_array2[31]));
        bufp->chgBit(oldp+306,(vlSymsp->TOP__top__DUT.__PVT__valid_array[0]));
        bufp->chgBit(oldp+307,(vlSymsp->TOP__top__DUT.__PVT__valid_array[1]));
        bufp->chgBit(oldp+308,(vlSymsp->TOP__top__DUT.__PVT__valid_array[2]));
        bufp->chgBit(oldp+309,(vlSymsp->TOP__top__DUT.__PVT__valid_array[3]));
        bufp->chgBit(oldp+310,(vlSymsp->TOP__top__DUT.__PVT__valid_array[4]));
        bufp->chgBit(oldp+311,(vlSymsp->TOP__top__DUT.__PVT__valid_array[5]));
        bufp->chgBit(oldp+312,(vlSymsp->TOP__top__DUT.__PVT__valid_array[6]));
        bufp->chgBit(oldp+313,(vlSymsp->TOP__top__DUT.__PVT__valid_array[7]));
        bufp->chgBit(oldp+314,(vlSymsp->TOP__top__DUT.__PVT__valid_array[8]));
        bufp->chgBit(oldp+315,(vlSymsp->TOP__top__DUT.__PVT__valid_array[9]));
        bufp->chgBit(oldp+316,(vlSymsp->TOP__top__DUT.__PVT__valid_array[10]));
        bufp->chgBit(oldp+317,(vlSymsp->TOP__top__DUT.__PVT__valid_array[11]));
        bufp->chgBit(oldp+318,(vlSymsp->TOP__top__DUT.__PVT__valid_array[12]));
        bufp->chgBit(oldp+319,(vlSymsp->TOP__top__DUT.__PVT__valid_array[13]));
        bufp->chgBit(oldp+320,(vlSymsp->TOP__top__DUT.__PVT__valid_array[14]));
        bufp->chgBit(oldp+321,(vlSymsp->TOP__top__DUT.__PVT__valid_array[15]));
        bufp->chgBit(oldp+322,(vlSymsp->TOP__top__DUT.__PVT__valid_array[16]));
        bufp->chgBit(oldp+323,(vlSymsp->TOP__top__DUT.__PVT__valid_array[17]));
        bufp->chgBit(oldp+324,(vlSymsp->TOP__top__DUT.__PVT__valid_array[18]));
        bufp->chgBit(oldp+325,(vlSymsp->TOP__top__DUT.__PVT__valid_array[19]));
        bufp->chgBit(oldp+326,(vlSymsp->TOP__top__DUT.__PVT__valid_array[20]));
        bufp->chgBit(oldp+327,(vlSymsp->TOP__top__DUT.__PVT__valid_array[21]));
        bufp->chgBit(oldp+328,(vlSymsp->TOP__top__DUT.__PVT__valid_array[22]));
        bufp->chgBit(oldp+329,(vlSymsp->TOP__top__DUT.__PVT__valid_array[23]));
        bufp->chgBit(oldp+330,(vlSymsp->TOP__top__DUT.__PVT__valid_array[24]));
        bufp->chgBit(oldp+331,(vlSymsp->TOP__top__DUT.__PVT__valid_array[25]));
        bufp->chgBit(oldp+332,(vlSymsp->TOP__top__DUT.__PVT__valid_array[26]));
        bufp->chgBit(oldp+333,(vlSymsp->TOP__top__DUT.__PVT__valid_array[27]));
        bufp->chgBit(oldp+334,(vlSymsp->TOP__top__DUT.__PVT__valid_array[28]));
        bufp->chgBit(oldp+335,(vlSymsp->TOP__top__DUT.__PVT__valid_array[29]));
        bufp->chgBit(oldp+336,(vlSymsp->TOP__top__DUT.__PVT__valid_array[30]));
        bufp->chgBit(oldp+337,(vlSymsp->TOP__top__DUT.__PVT__valid_array[31]));
        bufp->chgBit(oldp+338,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[0]));
        bufp->chgBit(oldp+339,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[1]));
        bufp->chgBit(oldp+340,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[2]));
        bufp->chgBit(oldp+341,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[3]));
        bufp->chgBit(oldp+342,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[4]));
        bufp->chgBit(oldp+343,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[5]));
        bufp->chgBit(oldp+344,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[6]));
        bufp->chgBit(oldp+345,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[7]));
        bufp->chgBit(oldp+346,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[8]));
        bufp->chgBit(oldp+347,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[9]));
        bufp->chgBit(oldp+348,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[10]));
        bufp->chgBit(oldp+349,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[11]));
        bufp->chgBit(oldp+350,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[12]));
        bufp->chgBit(oldp+351,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[13]));
        bufp->chgBit(oldp+352,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[14]));
        bufp->chgBit(oldp+353,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[15]));
        bufp->chgBit(oldp+354,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[16]));
        bufp->chgBit(oldp+355,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[17]));
        bufp->chgBit(oldp+356,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[18]));
        bufp->chgBit(oldp+357,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[19]));
        bufp->chgBit(oldp+358,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[20]));
        bufp->chgBit(oldp+359,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[21]));
        bufp->chgBit(oldp+360,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[22]));
        bufp->chgBit(oldp+361,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[23]));
        bufp->chgBit(oldp+362,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[24]));
        bufp->chgBit(oldp+363,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[25]));
        bufp->chgBit(oldp+364,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[26]));
        bufp->chgBit(oldp+365,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[27]));
        bufp->chgBit(oldp+366,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[28]));
        bufp->chgBit(oldp+367,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[29]));
        bufp->chgBit(oldp+368,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[30]));
        bufp->chgBit(oldp+369,(vlSymsp->TOP__top__DUT.__PVT__valid_array2[31]));
        bufp->chgBit(oldp+370,(vlSymsp->TOP__top__DUT.__PVT__lru_array[0]));
        bufp->chgBit(oldp+371,(vlSymsp->TOP__top__DUT.__PVT__lru_array[1]));
        bufp->chgBit(oldp+372,(vlSymsp->TOP__top__DUT.__PVT__lru_array[2]));
        bufp->chgBit(oldp+373,(vlSymsp->TOP__top__DUT.__PVT__lru_array[3]));
        bufp->chgBit(oldp+374,(vlSymsp->TOP__top__DUT.__PVT__lru_array[4]));
        bufp->chgBit(oldp+375,(vlSymsp->TOP__top__DUT.__PVT__lru_array[5]));
        bufp->chgBit(oldp+376,(vlSymsp->TOP__top__DUT.__PVT__lru_array[6]));
        bufp->chgBit(oldp+377,(vlSymsp->TOP__top__DUT.__PVT__lru_array[7]));
        bufp->chgBit(oldp+378,(vlSymsp->TOP__top__DUT.__PVT__lru_array[8]));
        bufp->chgBit(oldp+379,(vlSymsp->TOP__top__DUT.__PVT__lru_array[9]));
        bufp->chgBit(oldp+380,(vlSymsp->TOP__top__DUT.__PVT__lru_array[10]));
        bufp->chgBit(oldp+381,(vlSymsp->TOP__top__DUT.__PVT__lru_array[11]));
        bufp->chgBit(oldp+382,(vlSymsp->TOP__top__DUT.__PVT__lru_array[12]));
        bufp->chgBit(oldp+383,(vlSymsp->TOP__top__DUT.__PVT__lru_array[13]));
        bufp->chgBit(oldp+384,(vlSymsp->TOP__top__DUT.__PVT__lru_array[14]));
        bufp->chgBit(oldp+385,(vlSymsp->TOP__top__DUT.__PVT__lru_array[15]));
        bufp->chgBit(oldp+386,(vlSymsp->TOP__top__DUT.__PVT__lru_array[16]));
        bufp->chgBit(oldp+387,(vlSymsp->TOP__top__DUT.__PVT__lru_array[17]));
        bufp->chgBit(oldp+388,(vlSymsp->TOP__top__DUT.__PVT__lru_array[18]));
        bufp->chgBit(oldp+389,(vlSymsp->TOP__top__DUT.__PVT__lru_array[19]));
        bufp->chgBit(oldp+390,(vlSymsp->TOP__top__DUT.__PVT__lru_array[20]));
        bufp->chgBit(oldp+391,(vlSymsp->TOP__top__DUT.__PVT__lru_array[21]));
        bufp->chgBit(oldp+392,(vlSymsp->TOP__top__DUT.__PVT__lru_array[22]));
        bufp->chgBit(oldp+393,(vlSymsp->TOP__top__DUT.__PVT__lru_array[23]));
        bufp->chgBit(oldp+394,(vlSymsp->TOP__top__DUT.__PVT__lru_array[24]));
        bufp->chgBit(oldp+395,(vlSymsp->TOP__top__DUT.__PVT__lru_array[25]));
        bufp->chgBit(oldp+396,(vlSymsp->TOP__top__DUT.__PVT__lru_array[26]));
        bufp->chgBit(oldp+397,(vlSymsp->TOP__top__DUT.__PVT__lru_array[27]));
        bufp->chgBit(oldp+398,(vlSymsp->TOP__top__DUT.__PVT__lru_array[28]));
        bufp->chgBit(oldp+399,(vlSymsp->TOP__top__DUT.__PVT__lru_array[29]));
        bufp->chgBit(oldp+400,(vlSymsp->TOP__top__DUT.__PVT__lru_array[30]));
        bufp->chgBit(oldp+401,(vlSymsp->TOP__top__DUT.__PVT__lru_array[31]));
        bufp->chgCData(oldp+402,(vlSymsp->TOP__top__DUT.__PVT__spill_counter),5);
        bufp->chgCData(oldp+403,(vlSymsp->TOP__top__DUT.__PVT__flush_counter),7);
        bufp->chgCData(oldp+404,(vlSymsp->TOP__top__DUT.__PVT__refill_req_counter),5);
        bufp->chgCData(oldp+405,(vlSymsp->TOP__top__DUT.__PVT__refill_resp_counter),5);
        bufp->chgWData(oldp+406,(vlSymsp->TOP__top__DUT.__PVT__refill_data),512);
        bufp->chgWData(oldp+422,(vlSymsp->TOP__top__DUT.__PVT__data_array[0]),512);
        bufp->chgWData(oldp+438,(vlSymsp->TOP__top__DUT.__PVT__data_array[1]),512);
        bufp->chgWData(oldp+454,(vlSymsp->TOP__top__DUT.__PVT__data_array[2]),512);
        bufp->chgWData(oldp+470,(vlSymsp->TOP__top__DUT.__PVT__data_array[3]),512);
        bufp->chgWData(oldp+486,(vlSymsp->TOP__top__DUT.__PVT__data_array[4]),512);
        bufp->chgWData(oldp+502,(vlSymsp->TOP__top__DUT.__PVT__data_array[5]),512);
        bufp->chgWData(oldp+518,(vlSymsp->TOP__top__DUT.__PVT__data_array[6]),512);
        bufp->chgWData(oldp+534,(vlSymsp->TOP__top__DUT.__PVT__data_array[7]),512);
        bufp->chgWData(oldp+550,(vlSymsp->TOP__top__DUT.__PVT__data_array[8]),512);
        bufp->chgWData(oldp+566,(vlSymsp->TOP__top__DUT.__PVT__data_array[9]),512);
        bufp->chgWData(oldp+582,(vlSymsp->TOP__top__DUT.__PVT__data_array[10]),512);
        bufp->chgWData(oldp+598,(vlSymsp->TOP__top__DUT.__PVT__data_array[11]),512);
        bufp->chgWData(oldp+614,(vlSymsp->TOP__top__DUT.__PVT__data_array[12]),512);
        bufp->chgWData(oldp+630,(vlSymsp->TOP__top__DUT.__PVT__data_array[13]),512);
        bufp->chgWData(oldp+646,(vlSymsp->TOP__top__DUT.__PVT__data_array[14]),512);
        bufp->chgWData(oldp+662,(vlSymsp->TOP__top__DUT.__PVT__data_array[15]),512);
        bufp->chgWData(oldp+678,(vlSymsp->TOP__top__DUT.__PVT__data_array[16]),512);
        bufp->chgWData(oldp+694,(vlSymsp->TOP__top__DUT.__PVT__data_array[17]),512);
        bufp->chgWData(oldp+710,(vlSymsp->TOP__top__DUT.__PVT__data_array[18]),512);
        bufp->chgWData(oldp+726,(vlSymsp->TOP__top__DUT.__PVT__data_array[19]),512);
        bufp->chgWData(oldp+742,(vlSymsp->TOP__top__DUT.__PVT__data_array[20]),512);
        bufp->chgWData(oldp+758,(vlSymsp->TOP__top__DUT.__PVT__data_array[21]),512);
        bufp->chgWData(oldp+774,(vlSymsp->TOP__top__DUT.__PVT__data_array[22]),512);
        bufp->chgWData(oldp+790,(vlSymsp->TOP__top__DUT.__PVT__data_array[23]),512);
        bufp->chgWData(oldp+806,(vlSymsp->TOP__top__DUT.__PVT__data_array[24]),512);
        bufp->chgWData(oldp+822,(vlSymsp->TOP__top__DUT.__PVT__data_array[25]),512);
        bufp->chgWData(oldp+838,(vlSymsp->TOP__top__DUT.__PVT__data_array[26]),512);
        bufp->chgWData(oldp+854,(vlSymsp->TOP__top__DUT.__PVT__data_array[27]),512);
        bufp->chgWData(oldp+870,(vlSymsp->TOP__top__DUT.__PVT__data_array[28]),512);
        bufp->chgWData(oldp+886,(vlSymsp->TOP__top__DUT.__PVT__data_array[29]),512);
        bufp->chgWData(oldp+902,(vlSymsp->TOP__top__DUT.__PVT__data_array[30]),512);
        bufp->chgWData(oldp+918,(vlSymsp->TOP__top__DUT.__PVT__data_array[31]),512);
        bufp->chgWData(oldp+934,(vlSymsp->TOP__top__DUT.__PVT__data_array2[0]),512);
        bufp->chgWData(oldp+950,(vlSymsp->TOP__top__DUT.__PVT__data_array2[1]),512);
        bufp->chgWData(oldp+966,(vlSymsp->TOP__top__DUT.__PVT__data_array2[2]),512);
        bufp->chgWData(oldp+982,(vlSymsp->TOP__top__DUT.__PVT__data_array2[3]),512);
        bufp->chgWData(oldp+998,(vlSymsp->TOP__top__DUT.__PVT__data_array2[4]),512);
        bufp->chgWData(oldp+1014,(vlSymsp->TOP__top__DUT.__PVT__data_array2[5]),512);
        bufp->chgWData(oldp+1030,(vlSymsp->TOP__top__DUT.__PVT__data_array2[6]),512);
        bufp->chgWData(oldp+1046,(vlSymsp->TOP__top__DUT.__PVT__data_array2[7]),512);
        bufp->chgWData(oldp+1062,(vlSymsp->TOP__top__DUT.__PVT__data_array2[8]),512);
        bufp->chgWData(oldp+1078,(vlSymsp->TOP__top__DUT.__PVT__data_array2[9]),512);
        bufp->chgWData(oldp+1094,(vlSymsp->TOP__top__DUT.__PVT__data_array2[10]),512);
        bufp->chgWData(oldp+1110,(vlSymsp->TOP__top__DUT.__PVT__data_array2[11]),512);
        bufp->chgWData(oldp+1126,(vlSymsp->TOP__top__DUT.__PVT__data_array2[12]),512);
        bufp->chgWData(oldp+1142,(vlSymsp->TOP__top__DUT.__PVT__data_array2[13]),512);
        bufp->chgWData(oldp+1158,(vlSymsp->TOP__top__DUT.__PVT__data_array2[14]),512);
        bufp->chgWData(oldp+1174,(vlSymsp->TOP__top__DUT.__PVT__data_array2[15]),512);
        bufp->chgWData(oldp+1190,(vlSymsp->TOP__top__DUT.__PVT__data_array2[16]),512);
        bufp->chgWData(oldp+1206,(vlSymsp->TOP__top__DUT.__PVT__data_array2[17]),512);
        bufp->chgWData(oldp+1222,(vlSymsp->TOP__top__DUT.__PVT__data_array2[18]),512);
        bufp->chgWData(oldp+1238,(vlSymsp->TOP__top__DUT.__PVT__data_array2[19]),512);
        bufp->chgWData(oldp+1254,(vlSymsp->TOP__top__DUT.__PVT__data_array2[20]),512);
        bufp->chgWData(oldp+1270,(vlSymsp->TOP__top__DUT.__PVT__data_array2[21]),512);
        bufp->chgWData(oldp+1286,(vlSymsp->TOP__top__DUT.__PVT__data_array2[22]),512);
        bufp->chgWData(oldp+1302,(vlSymsp->TOP__top__DUT.__PVT__data_array2[23]),512);
        bufp->chgWData(oldp+1318,(vlSymsp->TOP__top__DUT.__PVT__data_array2[24]),512);
        bufp->chgWData(oldp+1334,(vlSymsp->TOP__top__DUT.__PVT__data_array2[25]),512);
        bufp->chgWData(oldp+1350,(vlSymsp->TOP__top__DUT.__PVT__data_array2[26]),512);
        bufp->chgWData(oldp+1366,(vlSymsp->TOP__top__DUT.__PVT__data_array2[27]),512);
        bufp->chgWData(oldp+1382,(vlSymsp->TOP__top__DUT.__PVT__data_array2[28]),512);
        bufp->chgWData(oldp+1398,(vlSymsp->TOP__top__DUT.__PVT__data_array2[29]),512);
        bufp->chgWData(oldp+1414,(vlSymsp->TOP__top__DUT.__PVT__data_array2[30]),512);
        bufp->chgWData(oldp+1430,(vlSymsp->TOP__top__DUT.__PVT__data_array2[31]),512);
        bufp->chgCData(oldp+1446,(vlSymsp->TOP__top__DUT.__PVT__unnamedblk1__DOT__i),6);
        bufp->chgCData(oldp+1447,(vlSymsp->TOP__top__DUT.__PVT__unnamedblk2__DOT__i),6);
        bufp->chgCData(oldp+1448,(vlSymsp->TOP__top__DUT.__PVT__unnamedblk3__DOT__i),6);
        bufp->chgCData(oldp+1449,(vlSymsp->TOP__top__DUT__spill_index_mux.__PVT__in1),5);
        bufp->chgWData(oldp+1450,(vlSymsp->TOP__top__DUT__darray_write_mux.__PVT__in1),512);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[6U])) {
        bufp->chgIData(oldp+1466,(vlSymsp->TOP__top__DUT.__PVT__cache_request_data_M0),32);
        bufp->chgWData(oldp+1467,(vlSymsp->TOP__top__DUT.__PVT__repl_cachereq_data),512);
        bufp->chgIData(oldp+1483,(vlSymsp->TOP__top__DUT__cache_request_data_reg_M0.__PVT__q),32);
        bufp->chgWData(oldp+1484,(vlSymsp->TOP__top__DUT__darray_write_mux.__PVT__in0),512);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[7U])) {
        bufp->chgIData(oldp+1500,(vlSymsp->TOP__top__DUT.__PVT__cache_request_addr_M0),32);
        bufp->chgIData(oldp+1501,(vlSymsp->TOP__top__DUT.__PVT__current_tag),21);
        bufp->chgCData(oldp+1502,(vlSymsp->TOP__top__DUT.__PVT__index_M0),5);
        bufp->chgCData(oldp+1503,(vlSymsp->TOP__top__DUT.__PVT__offset_M0),4);
        bufp->chgIData(oldp+1504,(vlSymsp->TOP__top__DUT.__PVT__z6b_result),32);
        bufp->chgSData(oldp+1505,(vlSymsp->TOP__top__DUT.__PVT__offset_write),16);
        bufp->chgIData(oldp+1506,(vlSymsp->TOP__top__DUT__cache_request_addr_reg_M0.__PVT__q),32);
        bufp->chgIData(oldp+1507,(vlSymsp->TOP__top__DUT__z6b_mux.__PVT__in0),32);
        bufp->chgIData(oldp+1508,(vlSymsp->TOP__top__DUT__z6b_mux.__PVT__in1),32);
        bufp->chgCData(oldp+1509,(vlSymsp->TOP__top__DUT__spill_index_mux.__PVT__in0),5);
        bufp->chgSData(oldp+1510,(vlSymsp->TOP__top__DUT__word_en_mux.__PVT__in1),16);
        bufp->chgCData(oldp+1511,(vlSymsp->TOP__top__DUT__output_mux.__PVT__sel),4);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[0xaU])) {
        bufp->chgWData(oldp+1512,(vlSymsp->TOP__top__DUT__way_output_sel_mux.__PVT__in0),512);
        bufp->chgWData(oldp+1528,(vlSymsp->TOP__top__DUT__way_output_sel_mux.__PVT__in1),512);
    }
    bufp->chgBit(oldp+1544,(vlSelf->clk));
    bufp->chgBit(oldp+1545,(vlSelf->linetrace));
    bufp->chgIData(oldp+1546,(vlSymsp->TOP__top__DUT.__PVT__z6b_mux_result),32);
    bufp->chgSData(oldp+1547,(vlSymsp->TOP__top__DUT.__PVT__write_word_enable),16);
    bufp->chgIData(oldp+1548,(vlSymsp->TOP__top__DUT__z6b_mux.__PVT__out),32);
    bufp->chgSData(oldp+1549,(vlSymsp->TOP__top__DUT__word_en_mux.__PVT__in0),16);
    bufp->chgSData(oldp+1550,(vlSymsp->TOP__top__DUT__word_en_mux.__PVT__out),16);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[4U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[5U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[6U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[7U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[8U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[9U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[0xaU] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[0xbU] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[0xcU] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[0xdU] = 0U;
}
